name: Build Static Binary

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cross tool
        uses: taiki-e/install-action@cross

      - name: Build Fully Static Binary
        env:
          RUSTFLAGS: "-C target-feature=+crt-static -C link-self-contained=yes"
          PKG_CONFIG_ALL_STATIC: "1"
          OPENSSL_STATIC: "1"
        run: cross build --release --target x86_64-unknown-linux-musl

      - name: Verify Binary Type (Xem log tại đây)
        run: |
          echo "=========================================="
          echo "KIỂM TRA LOẠI FILE TRỰC TIẾP TRÊN GITHUB:"
          file target/x86_64-unknown-linux-musl/release/bsgs
          echo "=========================================="

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: plutus_rust_musl_static
          path: target/x86_64-unknown-linux-musl/release/bsgs
